# This file contains values from Cookiecutter

default_context:
  project_name: "polars-playground"
  project_description: "comparison of polars performance to pandas on sagemaker compute optimised instance"
  organization: "playground"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "ryankarlos"
  email: "ryankarlos@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
